services:
  backend:
    image: madnolia-backend-dev
    build:
      context: ./Madnolia-Backend
      target: development

    ports:
      - 3000:3000
    volumes:
      - ./Madnolia-Backend:/app:Z
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - mongo
  
  mongo:
    image: mongo
    restart: always

    volumes:
      - mongo-data:/data/db
    ports:
      - 27017:27017
    command: mongod --replSet rs1 --bind_ip_all


volumes:
  mongo-data:
