services:
  backend:
    image: madnolia-backend-prod
    build:
      context: ./Madnolia-Backend
      dockerfile: Dockerfile
      target: production

    ports:
      - "3000:3000"
    env_file:
      - ./Madnolia-Backend/.env.production
    environment:
      - NODE_ENV=production
      - MONGODB_REPLICA_SET=


    restart: always
    volumes:
      - releases_data:/app/public/releases

volumes:
  releases_data:
